### ISSUE TITLE
Africa/Lome missing timezone

### ISSUE THREAD

**Issue by icnocop** [manuelmhtr/countries-and-timezones#1]
Hi.

Thank you for countries-and-timezones.

I noticed that the time zone "Africa/Lome" is missing from `data.json`.

http://www.timezoneconverter.com/cgi-bin/zoneinfo?tz=Africa/Lome
Country: Togo

This causes a call to `getCountriesForTimezone('Africa/Lome')` to return `[]`.

I expected it to return `[ { 'TG' } ]`

Thank you.

**Comment by manuelmhtr** [comment]
Hi @icnocop,
Thanks for the report. Version [`2.0.0`](https://github.com/manuelmhtr/countries-and-timezones/pull/6) added 167 timezone aliases, now `Africa/Lome` is included.

Thanks,
