### ISSUE TITLE
The "most relevant" timezone for a given country

### ISSUE THREAD

**Issue by gabrielcipriano** [manuelmhtr/countries-and-timezones#105]
Is there a way of telling the most popular (i.e. more people living) timezone of a given Country?

for example, If I want to infer a user timezone based on they country, let's say, France, it has 12 timezones.. of course UTC+1 is the most popular for France, with >90% of it's population living there. 

Is there a way of accomplish that with IANA data?

**Comment by manuelmhtr** [comment]
Hi @gabrielcipriano
This project is intended to be very minimalist and have minimum dependencies, so unfortunately is not posible.

But you can do it with another project I have: https://rapidapi.com/Spott/api/spott it's a places API. You can send the user IP and get the location of the user (which includes the time zone).
