### ISSUE TITLE
Include es5 format?

### ISSUE THREAD

**Issue by IgorWolbers** [manuelmhtr/countries-and-timezones#11]
Could you include an es5 format? The new v2.0.5 will fail on browsers like MS Edge that do not support es2015 syntax like the use of the spread operator. 

Your library is awesome, thank you for the hard work and maintenance.

**Comment by manuelmhtr** [comment]
Hi @IgorWolbers thanks for your comments!

Sure. Let me work this weekend to support es5.

**Comment by stevenvachon** [comment]
@manuelmhtr  I can create a PR for this. Would you prefer ES5 source code or a Babel build step?

**Comment by manuelmhtr** [comment]
Hi @stevenvachon, that would be amazing! I prefer the Babel step

**Comment by manuelmhtr** [comment]
ES5 support is available now in [v2.1.0](https://www.npmjs.com/package/countries-and-timezones/v/2.1.0).
Thanks for your help @stevenvachon!
