### ISSUE TITLE
npm run build not happening during package install

### ISSUE THREAD

**Issue by ravihara** [manuelmhtr/countries-and-timezones#18]
main field entry is pointed to src-es5/index.js which is to be generated by npm run build command. But, if we just use npm install --save countries-and-timzezones, we are not getting the src-es5 folder created and hence, the dependent code is throwing error.

**Comment by manuelmhtr** [comment]
Fixing ASAP!

**Comment by manuelmhtr** [comment]
Fixed now in [v2.1.1](https://www.npmjs.com/package/countries-and-timezones/v/2.1.1).
