### ISSUE TITLE
UK not Britain

### ISSUE THREAD

**Issue by alessandrovitale** [manuelmhtr/countries-and-timezones#2]
The name for "id": "GB" is not Britain (UK). According to https://en.wikipedia.org/wiki/ISO_3166-1 the name should be "United Kingdom of Great Britain and Northern Ireland" or at least "United Kingdom".

**Comment by manuelmhtr** [comment]
Hi @alessandrovitale ,
You are totally right. `GB` name is now "United Kingdom" in version [`2.0.0`](https://github.com/manuelmhtr/countries-and-timezones/pull/6).
