### ISSUE TITLE
[2.3.x] data.json missing from distribution

### ISSUE THREAD

**Issue by tminich** [manuelmhtr/countries-and-timezones#23]
Version 2.3.0 removed data.json from the distribution. We were using this file to have synchronized timezone data between front- and backend (php). It's not really feasible to parse the Javascript file for this purpose. Could you please revert that decision?

**Comment by manuelmhtr** [comment]
Hi @tminich 
Sorry for causing this problem. I removed it to make a single distribution file compatible with browsers. However the original file is available in `src/data.json`.

How are you importing the file in your PHP backend? If you are downloading the file, you can use the following link:
```sh
https://cdn.jsdelivr.net/gh/manuelmhtr/countries-and-timezones@v2.3.0/src/data.json
```
Or if you are cloning the repo you may require it directly from `src/data.json`.

Would any of those solutions work for you?

**Comment by tminich** [comment]
No need to be sorry, that's a fair argument. I'll work with the cdn url, thanks.
