### ISSUE TITLE
Invalid timezone for some countries.

### ISSUE THREAD

**Issue by mohit000001** [manuelmhtr/countries-and-timezones#29]
We are trying to get timezone for Russia. but we have found that it is giving W-SU for Russia. if we look into https://en.wikipedia.org/wiki/List_of_tz_database_time_zones 'W-SU' is Deprecated. Please update the timezones which have been Deprecated.

**Comment by manuelmhtr** [comment]
Hi @mohit000001,
That's true, thanks. It will be removed in the next version (this week).

**Comment by manuelmhtr** [comment]
Hi @mohit000001. I just released version `v3.0.0` which removes `W-SU` and other deprecated timezones.
