### ISSUE TITLE
Europe/Vaduz missing timezone

### ISSUE THREAD

**Issue by dptole** [manuelmhtr/countries-and-timezones#3]
While looking for a lib that tries to map timezones to countries I found this one and was filled with joy

Unfortunately there are no countries for the timezone [Europe/Vaduz][url-europe-vaduz]

It was supposed to show only "Liechtenstein"

Maybe https://www.zeitverschiebung.net/en/ could help you to expand your dataset

[url-europe-vaduz]: https://www.zeitverschiebung.net/en/timezone/europe--vaduz

**Comment by sheksushant** [comment]
No Country for "Asia/Calcutta" either

**Comment by manuelmhtr** [comment]
Hi @dptole and @sheksushant,
Thanks for the report. Version [`2.0.0`](https://github.com/manuelmhtr/countries-and-timezones/pull/6) added 167 timezone aliases, now `Europe/Vaduz` and `Asia/Calcutta` are included.

Thanks,
