### ISSUE TITLE
DST Observed Countries

### ISSUE THREAD

**Issue by z639** [manuelmhtr/countries-and-timezones#4]
Enhancement -- 

Maybe an boolean value added to the JSON file to indicate if the country does or does not use DST (daylight saving time).

**Comment by z639** [comment]
Actually, looking at the date.json, that might be trickier then I first thought.

**Comment by manuelmhtr** [comment]
Hi @z639 ,
You are right. It's valuable to know whether a timezone observes DST or not. Version [2.0.0](https://github.com/manuelmhtr/countries-and-timezones/pull/6) now introduces properties `dstOffset` and `dstOffsetStr` for all timezones.
