### ISSUE TITLE
Time zone abbreviations

### ISSUE THREAD

**Issue by dsbaars** [manuelmhtr/countries-and-timezones#43]
Nice work! I'm trying to get the abbreviations as well, although discouraged (https://en.wikipedia.org/wiki/List_of_time_zone_abbreviations). Are there any (semi-)official sources for that that you know of?

I did find this: https://github.com/sumitchawla/timezone-names

**Comment by manuelmhtr** [comment]
Hi @dsbaars,
Paul Eggert, tracks IANA timezones database in this repo: [eggert/tz](https://github.com/eggert/tz). I think is the most official -and readable- source out there.

In that repo, I found references to the abbreviations [here](https://github.com/eggert/tz/blob/aa9c4662f1801852408f8db1e082b2a429938648/theory.html) and [here](https://github.com/eggert/tz/blob/aa9c4662f1801852408f8db1e082b2a429938648/backzone).

Hope it helps!
