### ISSUE TITLE
Why does 'America/Toronto' return the Bahamas as a country?

### ISSUE THREAD

**Issue by z0ccc** [manuelmhtr/countries-and-timezones#46]
Hi,
Why does 'America/Toronto' return the Bahamas as a country? Shouldnt it be 'America/Nassau'?

Thanks

**Comment by manuelmhtr** [comment]
Hi @z0ccc,
`America/Nassau` is a deprecated timezone. Now `America/Toronto` is used as official timezone in Bahamas.

You can verify it here: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
