### ISSUE TITLE
Asia/Saigon doesn't exist, even though my browser doesn't agree

### ISSUE THREAD

**Issue by vacuumdreams** [manuelmhtr/countries-and-timezones#5]
if I do this in my console, the timezone returned is one which is missing from the dataset.

```
Intl.DateTimeFormat().resolvedOptions().timeZone
"Asia/Saigon"
```

unfortunately that doesn't match any of the timezones assigned to Vietnam in the json file:

```
    "VN": {
      "id": "VN",
      "name": "Vietnam",
      "timezones": [
        "Asia/Bangkok",
        "Asia/Ho_Chi_Minh"
      ]
    },
```

**Comment by manuelmhtr** [comment]
Hi @vacuumdreams ,
Thanks for the report. Version [`2.0.0`](https://github.com/manuelmhtr/countries-and-timezones/pull/6) added 167 timezone aliases, now `Asia/Saigon` is included.

Thanks,
