### ISSUE TITLE
Invalid uctOffset for America/St_Johns and Pacific/Marquesas

### ISSUE THREAD

**Issue by dmrayt** [manuelmhtr/countries-and-timezones#51]
Two timezones have the right utcOffsetStr but wrong utcOffset

| timezone | utcOffsetStr | wrong utcOffset | correct utcOffset |
|----------|--------------|-----------------|-------------------|
| America/St_Johns | -03:30 | -150 | -210 |
| Pacific/Marquesas | -09:30 | -510 | -570 |

**Comment by manuelmhtr** [comment]
Thanks for reporting the problem. It has been fixed in [v3.4.0](https://github.com/manuelmhtr/countries-and-timezones/releases/tag/v3.4.0)
