### ISSUE TITLE
DST Changes

### ISSUE THREAD

**Issue by Aryagopakumar** [manuelmhtr/countries-and-timezones#52]
Does the library account for DST changes through out the year? It does not seem so. 
Currently it is showing GMT -5 for America / Chicago. But it should be GMT -6 as DST is not active now
![image](https://user-images.githubusercontent.com/36843143/214492943-72ed60b6-1827-41ea-a4b5-5a9451b7d592.png)

![image](https://user-images.githubusercontent.com/36843143/214493040-eec50391-331c-49fe-84d4-0ba76dedfd0f.png)

**Comment by Aryagopakumar** [comment]
Or is it the user's responsibility to change the flag accordingly?

**Comment by manuelmhtr** [comment]
Hi @Aryagopakumar 
This library does not changes DST through the year., it is only informative. To track DST changes during the year I recommend more complex libraries such as [Luxon](https://moment.github.io/luxon/#/) or [Intl](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl).

**Comment by Aryagopakumar** [comment]
Thank you for your response
