### ISSUE TITLE
`getOffsetStr()` evaluates incorrectly for negative values

### ISSUE THREAD

**Issue by dondevi** [manuelmhtr/countries-and-timezones#60]
### The problem

The `utcOffset` of `Pacific/Marquesas` is `-570`, but `utcOffsetStr` returns `-10:30`.

### What is expected

The `utcOffsetStr` returns `-09:30`.

### What is happening

The code in `src/build-timezone.js`

```js
function getOffsetStr(offset) {
  const hours = Math.floor(offset / 60);  // There may be a calculation error here
  const min = offset % 60;
  const sign = offset < 0 ? '-' : '+';

  return `${sign}${getNumStr(hours)}:${getNumStr(min)}`;
}
```

This evaluates incorrectly for negative values

```js
Math.floor(570 / 60); // 9
Math.floor(-570 / 60); // -10
```

### Suggest to fix

```js
const hours = Math.floor(Math.abs(offset) / 60);
// or
const hours = ~~(offset / 60);
```

**Comment by manuelmhtr** [comment]
Hi @dondevi thanks a lot for reporting this issue and proposing a solution. It has been fixed in [v3.5.2](https://github.com/manuelmhtr/countries-and-timezones/releases/tag/v3.5.2)
