### ISSUE TITLE
Update to 2023c IANA db

### ISSUE THREAD

**Issue by ekrismer** [manuelmhtr/countries-and-timezones#61]
Any plans on updating the project to the latest version of the [IANA db](https://www.iana.org/time-zones) `2023c`?

Also thank you very much for this awesome lib! :)

**Comment by ekrismer** [comment]
I've just read the [announcements for `2023c`](https://mm.icann.org/pipermail/tz-announce/2023-March/000079.html) and realized that it essentially reverts the IANA db to `2023a`.

> This release's code and data are identical to 2023a.  In other words, 
> this release reverts all changes made in 2023b other than commentary, as 
> that appears to be the best of a bad set of short-notice choices for 
> modeling this week's daylight saving chaos in Lebanon.

Sorry for bringing this up.

**Comment by manuelmhtr** [comment]
Hi @ekrismer no problem. It's still a good practice to get it up to date; also found DST was missing to the `Nuuk` timezone. [v3.6.0](https://github.com/manuelmhtr/countries-and-timezones/releases/tag/v3.6.0)
Thanks!
