### ISSUE TITLE
Wrong utcOffset for Dublin

### ISSUE THREAD

**Issue by wickedest** [manuelmhtr/countries-and-timezones#62]
Thanks for this module! Trying to use it and the very first example I used was Dublin, but the answer looks wrong.

```js
ct.getTimezone('Europe/Dublin')
```

yields:

```js
{
    name: 'Europe/Dublin',
    countries: [ 'IE' ],
    utcOffset: 60,
    utcOffsetStr: '+01:00',
    dstOffset: 0,
    dstOffsetStr: '+00:00',
    aliasOf: null
}
```

The [UTC for Dublin is 0](https://www.zeitverschiebung.net/en/timezone/europe--dublin), whereas the DST can be +1.

**Comment by manuelmhtr** [comment]
Fixed in #69
