### ISSUE TITLE
Kosovo as a country is missing

### ISSUE THREAD

**Issue by navaneethakrishnan-gopalakrishnan** [manuelmhtr/countries-and-timezones#64]
![anysnap-04-jan-2024-at-9-00-57-pm](https://github.com/manuelmhtr/countries-and-timezones/assets/3315414/27d1e36a-fc08-455b-87f6-66f230e495cb)

Eventhough the **IANA** maintained Time Zone database lists Kosovo under **Europe/Belgrade**, the list of countries returned on **countries-and-timezones** library for **Europe/Belgrade** is missing **Kosovo**.

Kindly do the needful to include the country info of **Kosovo**.

**Comment by manuelmhtr** [comment]
I'm sorry but I can't until Kosovo has and official ISO8601 code and it gets listed in [public timezone lists](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)
