### ISSUE TITLE
Updating to the latest IANA db

### ISSUE THREAD

**Issue by jcfranco** [manuelmhtr/countries-and-timezones#68]
First off, thanks for this amazing library—it’s been really useful!

I wanted to ask about the best way to update the IANA database. Should we reach out to you directly? I wanted to submit a PR to update the database, but I couldn’t find a script in the repo to generate `data.json`, nor a way to pull this file from the sources of truth mentioned [here](https://github.com/manuelmhtr/countries-and-timezones/issues/42#issuecomment-929748237). Any guidance on this would be appreciated!

**Comment by manuelmhtr** [comment]
Thanks for your help!
I added some contributing steps [in the generator](https://app.yotepresto.com/sign-in/).

**Comment by jcfranco** [comment]
Awesome, thanks for the updated contribution steps!
