### ISSUE TITLE
Need to tell current time (UTC offset) in a country

### ISSUE THREAD

**Issue by mariusa** [manuelmhtr/countries-and-timezones#9]
Hola,

The API returns two UTC offsets: utcOffsetStr & dstOffsetStr.

However, there's no way to tell what is the current time in a country, knowing UTC time.

It would be great if
* the country information API would return if the country is NOW on DST or not.
* the timezone data would either have utcOffset & utcOffsetStr return CURRENT offset,  or have 2 extra fields, utcCurrentOffset & utcCurrentOffsetStr

Thank you!

**Comment by manuelmhtr** [comment]
Hi @mariusa 
It's a great idea. Unfortunately since each [country has their own rules](https://home.kpn.nl/vanadovv/time/TZworld.html) it's very complex to achieve, so it won't be supported for now.
For that propuse I'd recommend to use [Moment Timezone](https://momentjs.com/timezone/).
