### ISSUE TITLE
export error reported on 3.7.1 version

### ISSUE THREAD

**Issue by futin** [manuelmhtr/countries-and-timezones#91]
Still trying to figure out the major difference between 3.7.0 and 3.7.1 (as everything works fine with 3.7.0),  but I am not able to use the library without downgrade to 3.7.0.

My projects are using `type: module` in package.json, and the node version is `v20.12.1`.

Usage:

```
import Timezones from 'countries-and-timezones'
```

Error:

```
(node:55237) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
  Uncaught exception in test/spec/BaseModel.spec.js

  /.../node_modules/countries-and-timezones/esm/index.js:4175
  export { utils as default, getAllCountries, getAllTimezones, getCountriesForTimezone, getCountry, getCountryForTimezone, getTimezone, getTimezonesForCountry };
  ^^^^^^

  SyntaxError: Unexpected token 'export'
```

Up until now I had no issues.

Let me know if anyone can assist.

**Comment by thelinuxlich** [comment]
Also having similar issues after updating from `3.6.0`

**Comment by jcfranco** [comment]
@manuelmhtr It looks like [`esm/package.json` is missing](https://npmdiff.dev/countries-and-timezones/3.7.0/3.7.1/).

**Comment by jcfranco** [comment]
@thelinuxlich Did you experience the same issue after upgrading to 3.7.0 or 3.7.1?

**Comment by thelinuxlich** [comment]
Yes!

**Comment by manuelmhtr** [comment]
Hi @thelinuxlich @futin sorry about this problem. It should be fixed in [3.7.2](https://github.com/manuelmhtr/countries-and-timezones/releases/tag/v3.7.2).

Could you try it and confirm if it's working now?

**Comment by thelinuxlich** [comment]
Just tested and it's working!

**Comment by manuelmhtr** [comment]
Thank you!
